services:
  spice:
    image: ghcr.io/spiceai/spiceai:latest
    working_dir: /app
    command: ["--http", "0.0.0.0:8090", "--flight", "0.0.0.0:50051", "/app"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8090:8090"
      - "50051:50051"
    volumes:
      - ./:/app
